services:
  client:
    build:
      context: ./client
    container_name: car_gallery_client
    ports:
      - 3000:3000
    links:
      - api
    networks:
      - app-network
  mysql:
    container_name: car_gallery_db
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - app-network

  api:
    build:
      context: ./server
    container_name: car_gallery_api
    environment:
      - DATABASE_HOST=car_gallery_db
    ports:
      - 8080:8080
    links:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local
